name: Singleplayer Windows

on: 
  push:
    paths:
      - '.github/**'
      - 'sp/src/**'
  pull_request:
   paths:
      - 'sp/src/**'

jobs:
  build:
    name: Build Singleplayer Windows Binaries
    runs-on: windows-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure Dependencies
        uses: ilammy/msvc-dev-cmd@v1
        
      - name: Create Project
        working-directory: sp/src
        run: devtools/bin/vpc.exe /sdk2013ce /2013 +game /mksln sdk2013ce.sln

      - name: Build Project
        working-directory: sp/src      
        run: devenv sdk2013ce.sln /Build Release

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sp_sdk2013ce_windows
          path: sp/game/mod_sdk2013ce/bin/*